In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Coordinate origin
camera_origin = np.array([0, 0, 0])
gripper_origin = np.array([0.1, -0.05, 0.1])  # example t_cam2gripper

# Pixel ray (after inverse intrinsics)
direction = np.array([normalized_coords[0], normalized_coords[1], 1])
direction = direction / np.linalg.norm(direction)

# Scaled point in camera frame
point_camera = direction * known_Z

# Setup plot
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Draw camera ray
ax.quiver(*camera_origin, *direction, length=known_Z, color='b', label='Camera ray')

# Mark projected 3D point
ax.scatter(*point_camera, color='r', label='3D point in camera frame')

# Mark gripper origin
ax.scatter(*gripper_origin, color='g', label='Gripper origin')

# Labels
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
ax.set_title('Projection of 2D image point into 3D space')

plt.legend()
plt.show()

NameError: name 'normalized_coords' is not defined

In [6]:
import cv2 as cv
import numpy as np
import serial
import time
import logging
import ur
from urData import URData
import camera


camera = camera.Camera()
camera.connect(1, 1280, 720)
camera.initSlider()

times = 1000

while times > 0:
    #current_pose = receiver.get_pose()
    #print("Pose:", current_pose)
    
    camera.capture(600)
    times = times - 1







Points:  [-59. -80. 244.   1.] [ -1. -68. 254.   1.]
Points:  [-59. -80. 243.   1.] [ -1. -68. 253.   1.]
Points:  [-59. -80. 244.   1.] [ -1. -68. 254.   1.]
Points:  [-59. -80. 243.   1.] [ -1. -68. 253.   1.]
Points:  [-59. -81. 244.   1.] [ -1. -68. 254.   1.]
Points:  [-59. -80. 244.   1.] [ -1. -68. 254.   1.]
Points:  [-59. -80. 244.   1.] [ -1. -68. 254.   1.]
Points:  [-59. -80. 243.   1.] [ -1. -68. 253.   1.]
Points:  [-59. -81. 244.   1.] [ -1. -68. 254.   1.]
Points:  [-59. -80. 244.   1.] [ -1. -68. 254.   1.]
Points:  [-59. -81. 244.   1.] [ -1. -68. 254.   1.]
Points:  [-59. -80. 243.   1.] [ -1. -68. 253.   1.]
Points:  [-59. -80. 244.   1.] [ -1. -68. 254.   1.]
Points:  [-59. -80. 244.   1.] [ -1. -68. 254.   1.]
Points:  [-59. -80. 243.   1.] [ -1. -67. 253.   1.]
Points:  [-59. -81. 244.   1.] [ -1. -68. 254.   1.]
Points:  [-59. -81. 244.   1.] [ -1. -68. 254.   1.]
Points:  [-59. -81. 244.   1.] [ -1. -68. 254.   1.]
Points:  [-59. -80. 243.   1.] [ -1. -67. 253.

In [4]:
import cv2 as cv
import time
import numpy as np
import math
import re

import serial
import time
import logging
import camera

Camera = camera.Camera()

R = Camera.R_cam2gripper
print(np.dot(R, R.T))

[[1.00000001e+00 5.79454039e-10 3.04109159e-09]
 [5.79454039e-10 9.99999998e-01 1.95623041e-09]
 [3.04109159e-09 1.95623041e-09 9.99999990e-01]]
